//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjenploEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int idProducto { get; set; }
        public string nomProd { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
